name: Build Windows Release

# 工作流触发条件：手动触发或推送到 master 分支
on:
  workflow_dispatch:      # 手动触发（在 Actions 页面点击 Run workflow）
  push:
    branches: [ master ]  # 当 master 分支有推送时自动运行

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 托管的 Windows Runner

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装并配置 Flutter
      #    使用 subosito/flutter-action 可以指定版本并启用缓存
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.0'   # 与项目要求的 Flutter 版本一致
          cache: true

      # 3. 安装项目依赖
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get

      # 4. 构建 Windows 版本 (Release)
      - name: Build Windows executable
        run: |
          cd simple_live_app
          flutter build windows --release

      # 5. 上传构建产物，方便在 GitHub 页面下载
      - name: Upload artifact
      # v3 已弃用，使用 v4 版
        uses: actions/upload-artifact@v4
        with:
          # 文件名或压缩包名称，可自由修改
          name: SimpleLive-Windows
          # 需要上传的路径，指向生成的 Release 目录
          path: simple_live_app/build/windows/runner/Release
