name: Build Windows Release

on:
  workflow_dispatch:        # 允许在 Actions 页面手动触发
  push:
    branches: [ master ]    # 当 master 分支有推送时自动触发

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 Flutter （指定版本，可根据项目需要调整）
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.0'
          cache: true

      # 安装依赖
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get

      # 构建 Windows Release
      - name: Build Windows executable
        run: |
          cd simple_live_app
          flutter build windows --release

      # 上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLive-Windows
          # 使用通配符，以适配 Flutter 3.16+ 新增的架构目录
          path: simple_live_app/build/windows/**/runner/Release
