name: Build Windows Release

on:
  workflow_dispatch:      # 手动触发构建
  push:
    branches: [ master ]  # 当 master 分支有推送时自动触发

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 提供的 Windows Runner

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 第二步：配置 Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.0'   # 根据项目要求指定版本
          cache: true

      # 第三步：安装项目依赖
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get

      # 第四步：编译 Windows 版本
      - name: Build Windows executable
        run: |
          cd simple_live_app
          flutter build windows --release

      # 第五步：上传产物，供下载
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SimpleLive-Windows
          path: simple_live_app/build/windows/runner/Release
